# Generated by Django 3.1.1 on 2020-09-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='numOrganisation',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
