# Generated by Django 3.1.1 on 2020-09-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnet', '0002_auto_20200922_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='id',
        ),
        migrations.AlterField(
            model_name='compte',
            name='numero',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
