# Generated by Django 3.1.1 on 2020-09-23 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carnet', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarnetCheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=10)),
                ('dateCreation', models.DateTimeField(null=True)),
                ('agentCreation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnet.compte')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
