# Generated by Django 3.1.1 on 2020-09-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnet', '0005_auto_20200923_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carnetcheque',
            old_name='dateCreation',
            new_name='date_Creation',
        ),
        migrations.RemoveField(
            model_name='carnetcheque',
            name='agentCreation',
        ),
        migrations.AddField(
            model_name='carnetcheque',
            name='agent_Creation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carnetcheque',
            name='agent_Emission',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carnetcheque',
            name='agent_Impression',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carnetcheque',
            name='date_Emission',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='carnetcheque',
            name='date_Impression',
            field=models.DateTimeField(null=True),
        ),
    ]
