# Generated by Django 3.1.1 on 2020-09-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carnet', '0010_cheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeBV',
            fields=[
                ('numero', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('statut', models.CharField(max_length=10)),
                ('carnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnet.carnetcheque')),
            ],
        ),
        migrations.CreateModel(
            name='CarnetBV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=10)),
                ('date_Creation', models.DateTimeField(null=True)),
                ('id_agent_Creation', models.IntegerField(null=True)),
                ('date_Impression', models.DateTimeField(null=True)),
                ('id_agent_Impression', models.IntegerField(null=True)),
                ('date_Emission', models.DateTimeField(null=True)),
                ('id_agent_Emission', models.IntegerField(null=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnet.compte')),
            ],
        ),
    ]
