# Generated by Django 3.1.1 on 2020-09-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carnet', '0011_carnetbv_chequebv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequebv',
            name='carnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnet.carnetbv'),
        ),
    ]
