# Generated by Django 3.1.1 on 2020-10-15 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carnet', '0012_auto_20200924_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnetbv',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carnet_bvs', to='carnet.compte'),
        ),
        migrations.AlterField(
            model_name='carnetcheque',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carnet_cheques', to='carnet.compte'),
        ),
    ]
