# Generated by Django 3.1.1 on 2020-10-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnet', '0013_auto_20201015_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='numOrganisation',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
