# Generated by Django 3.1.1 on 2020-10-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnet', '0014_auto_20201015_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='numOrganisation',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name="Numero d'organisation"),
        ),
        migrations.AlterField(
            model_name='compte',
            name='numero',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Numero du compte'),
        ),
    ]
