# Generated by Django 3.1.1 on 2021-01-15 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carnet', '0015_auto_20201015_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carnetbv',
            options={'verbose_name': 'Carnet de BV', 'verbose_name_plural': 'Carnet de BV'},
        ),
        migrations.AlterModelOptions(
            name='carnetcheque',
            options={'verbose_name': 'Carnet de Cheque'},
        ),
        migrations.AlterModelOptions(
            name='chequebv',
            options={'verbose_name': 'Cheque de BV', 'verbose_name_plural': 'Cheque de BV'},
        ),
    ]
